name: Readme Stats
description: Text-based GitHub Readme Stats

inputs:
  token:
    description: GitHub Token
    default: ${{ github.token }}
  user-name:
    description: User Name
    default: ${{ github.repository_owner }}
  target:
    description: "Path to the target file to write stats into"
    default: "README.md"
  template:
    description: "Path to a template file to copy to target before writing stats"

runs:
  using: node24
  main: dist/index.js
