name: Readme Stats
description: Text-based GitHub Readme Stats

inputs:
  token:
    description: GitHub Token
    default: ${{ github.token }}
  user-name:
    description: User Name
    default: ${{ github.repository_owner }}
  target:
    description: ""
    default: "README.md"
  template:
    description: ""

runs:
  using: node20
  main: dist/index.js
