name: Readme Stats
description: Text-based GitHub Readme Stats

inputs:
  token:
    description: GitHub Token
    default: ${{ github.token }}
  user-name:
    description: User Name
    default: ${{ github.repository_owner }}

runs:
  using: node16
  main: dist/index.js
