name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - run: pnpm install --frozen-lockfile
      - name: Check
        run: pnpm check
      - name: Test
        run: pnpm test run
      - name: Build
        run: pnpm build
      - name: Verify dist is up to date
        run: git diff --exit-code dist/
